### ISSUE TITLE
Change risk categories

### ISSUE THREAD

**Issue by crobarcro** [eXolnet/redmine-risks#13]
Hello, thanks for this great plugin.

Is it possible to change the default risk categories? If so, what is the procedure?

e.g. to add a 'commercial' risk category

**Comment by xel1045** [comment]
Unfortunately, this is not currently possible to do it, but I think it could be a good addition.

**Comment by xel1045** [comment]
I just remember that this feature is already available. You can update risks categories in the Enumerations section of the admin.
