### ISSUE TITLE
Error at creating new risk

### ISSUE THREAD

**Issue by ccolussi** [eXolnet/redmine-risks#20]
Log file:

Started GET "/projects/foo/risks/new" for 192.168.1.58 at 2021-09-17 13:30:50 -0300
Processing by RisksController#new as HTML
  Parameters: {"project_id"=>"foo"}
  Current user: steve.carrell (id=5)
Completed 500 Internal Server Error in 94ms (ActiveRecord: 38.8ms)
  
ArgumentError (wrong number of arguments (given 2, expected 0..1)):
  
plugins/redmine_risks/app/controllers/risks_controller.rb:205:in `build_new_risk_from_params'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by wforte88** [comment]
[+1]

I have the same error in Redmine 4.2

**Comment by ccolussi** [comment]
It seems to a incompatibility with vault plugin -> https://noshutdown.ru/en/redmine-plugins-vault/, or another that you use.
So, isn't an error in this plugin.

**Comment by xel1045** [comment]
Thanks @ccolussi to have found the incompatibility.

**Comment by wforte88** [comment]
Thanks @ccolussi 
I found another incompatibility with this plugin https://www.redmine.org/plugins/redmine_periodic_task
