### ISSUE TITLE
Version 5.0

### ISSUE THREAD

**Issue by formigadiablo** [eXolnet/redmine-risks#24]
I am trying to install this plugin and I am finding this error:

Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 6.1.7)

  In Gemfile:
    rails (= 6.1.7) x86_64-linux was resolved to 6.1.7, which depends on
      activerecord (= 6.1.7) x86_64-linux

    state_machines-activerecord (~> 0.5.1) x86_64-linux was resolved to 0.5.2, which depends on
      activerecord (< 6.0, >= 4.1) x86_64-linux

**Comment by xel1045** [comment]
It will be fixed in the next release. Thanks!

**Comment by xel1045** [comment]
It's released.
