### ISSUE TITLE
No categories

### ISSUE THREAD

**Issue by ovhk** [eXolnet/redmine-risks#27]
Hi,

I'm on Redmine 5.1.1 and I can't create, edit, or display, any categories. It doesn't appear in the form or in the context menu. I only see the colomn on the main page list, but empty.

Thanks for your help,

BR,

**Comment by ashrafalzyoud** [comment]
It's compilable with redmine 5

**Comment by xel1045** [comment]
Categories can be configured through the Enumerations setting page.
