### ISSUE TITLE
Destroy risks on two projets in the same time

### ISSUE THREAD

**Issue by skalimer0** [eXolnet/redmine-risks#29]
**Describe the bug**
The destroy function on risks_controller use @project who're null if risks to destroy aren't on the same projet.

**To Reproduce**
1. Destroy risks on two projets in the same time (with the multi-selection)

**Expected behavior**
Stay on the same page without 500 error

**Comment by skalimer0** [comment]
A solution can will be : 
`redirect_back_or_default(@project.nil? ? nil : project_risks_path(@project))`

**Comment by xel1045** [comment]
v1.6.4 should fix your problem. Thanks to bringing it to my attention.
