### ISSUE TITLE
Internal Error when creating new Risk

### ISSUE THREAD

**Issue by feanorelf** [eXolnet/redmine-risks#6]
I have installed Redmine 4.0.4 with ruby 2.6.5 on a Windows 7 machine.

Whenever I try to create a new risk I receive an internal error message.

The log files says:

Completed 500 Internal Server Error in 19ms (ActiveRecord: 6.7ms)
  
ArgumentError (wrong number of arguments (given 2, expected 1)):
  
plugins/redmine_risks/app/models/risk.rb:166:in `assign_attributes'
plugins/redmine_risks/app/models/risk.rb:219:in `safe_attributes='
plugins/redmine_risks/app/controllers/risks_controller.rb:212:in `build_new_risk_from_params'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by xel1045** [comment]
It should now be fixed. Could you test release v1.1.2? Thanks!

**Comment by feanorelf** [comment]
Now it works. Thanks.
