### ISSUE TITLE
Redmine error 500, after close the risk

### ISSUE THREAD

**Issue by vvbasti** [eXolnet/redmine-risks#7]
**Describe the bug**
After close and safe the risk data entry, come direct a error 500 for display an view the entry.

**To Reproduce**
1. Create a new risk
2. Add details an data
3. change state from open to close
4. See error 500

**Redmine Details**
Environment:
  Redmine version                3.4.6.stable.17615
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  additionals                    2.0.20
  clipboard_image_paste          1.13
  computed_custom_field          1.0.7
  customfield_checkbox_utility   0.0.2
  hide_journal_details           0.0.2
  pdf_export_redmine             0.0.2
  recurring_tasks                2.0.0-pre
  redmine_banner                 0.1.2
  redmine_ckeditor               1.1.7
  redmine_custom_css             0.1.7
  redmine_impersonate            1.0.0
  redmine_issue_templates        0.2.1
  redmine_issue_todo_lists       1.2
  redmine_ldap_sync              2.1.0
  redmine_risks                  1.1.2
  redmine_subtask_list_accordion 1.3.2
  redmine_workflow_hidden_fields 0.5.0
  redmineup_tags                 2.0.4
  view_customize                 2.1.0

**Comment by xel1045** [comment]
Thanks for filling this issue! I'm having trouble reproducing, though. I've tested with the same version of Redmine (v3.4.6) and Risks (v1.1.2) that you are using.

Is there any other information you can provide that would help me out? Maybe the logs of the error?

**Comment by vvbasti** [comment]
Hy, i have solved the issue by remove the redmine_workflow_hidden_fields Plugin, 
The log list the follow errors with the installed Plugin.
https://github.com/alexwais/redmine_workflow_hidden_fields/releases

NoMethodError (undefined method `hidden_attribute?' for nil:NilClass):
  plugins/redmine_workflow_hidden_fields/lib/redmine_workflow_hidden_fields/journal_patch.rb:17:in `block in visible_details_with_hidden'
  plugins/redmine_workflow_hidden_fields/lib/redmine_workflow_hidden_fields/journal_patch.rb:15:in `select'
  plugins/redmine_workflow_hidden_fields/lib/redmine_workflow_hidden_fields/journal_patch.rb:15:in `visible_details_with_hidden'
  plugins/redmine_risks/app/models/risk.rb:291:in `block in visible_journals_with_index'
  plugins/redmine_risks/app/models/risk.rb:291:in `select!'
  plugins/redmine_risks/app/models/risk.rb:291:in `visible_journals_with_index'
  plugins/redmine_risks/app/controllers/risks_controller.rb:67:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

That was a side effect, you have a tipp what i can do for solve for use booth pugins ?
My version for the hidden_fields was 0.5

**Comment by xel1045** [comment]
With the given error logs, I guess that `redmine_workflow_hidden_fields` suppose that only Redmine issues could be journalized.

The best would be to propose a pull request to this plugin to fix how journal are patched. In `journal_patch.rb`, they should add something like this:

```ruby
    def visible_details_with_hidden(user=User.current)
        dets = visible_details_without_hidden(user)
        return dets unless issue.is_a?(Issue)
        // ...
```
https://github.com/alexwais/redmine_workflow_hidden_fields/blob/master/lib/redmine_workflow_hidden_fields/journal_patch.rb#L14
