### ISSUE TITLE
500 after entering "Risks" tab

### ISSUE THREAD

**Issue by postmxa** [eXolnet/redmine-risks#8]
**Describe the bug**
when I go to Risk tab I get:
500
An error occurred while executing the query and has been logged. Please report this error to your Redmine administrator.

**To Reproduce**
1. Go to project where you enabled Risk module
2. Click on tab RISK
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/54929809/76398725-ac3d9400-637d-11ea-8e72-ffd2e16d2747.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]chrome, ie

**Comment by postmxa** [comment]
I restore from backup and do installation again. It works fine now.

**Comment by xel1045** [comment]
If it happens again, can you provide use the error message shown in `log/production.log` and we'll reopen the bug. Thanks!
