### ISSUE TITLE
A nother Side Effekt with Plugins 

### ISSUE THREAD

**Issue by vvbasti** [eXolnet/redmine-risks#9]
After a Risk creation comes the Redmine 500 error,

ActionView::Template::Error (no implicit conversion of nil into String):
    32:         <% end %>
    33:         <tr id="risk-<%= risk.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= risk.css_classes %>">
    34:           <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", risk.id, false, :id => nil) %></td>
    35:           <% query.inline_columns.each do |column| %>
    36:             <%= content_tag('td', column_content(column, risk), :class => column.css_classes) %>
    37:           <% end %>
    38:         </tr>
  plugins/redmine_risks/app/models/risk.rb:231:in `+'
  plugins/redmine_risks/app/models/risk.rb:231:in `magnitude'
  app/models/query.rb:69:in `value_object'
  app/helpers/queries_helper.rb:199:in `column_content'
  plugins/redmine_tags/lib/redmine_tags/patches/queries_helper_patch.rb:23:in `column_content_with_redmine_tags'
  plugins/redmine_risks/app/views/risks/_list.html.erb:35:in `block (3 levels) in _2b955d32d83860aab334e965cd2aecff'
  plugins/redmine_risks/app/views/risks/_list.html.erb:34:in `each'
  plugins/redmine_risks/app/views/risks/_list.html.erb:34:in `block (2 levels) in _2b955d32d83860aab334e965cd2aecff'
  app/helpers/queries_helper.rb:140:in `block in grouped_query_results'
  app/helpers/queries_helper.rb:125:in `each'
  app/helpers/queries_helper.rb:125:in `grouped_query_results'
  plugins/redmine_risks/app/views/risks/_list.html.erb:20:in `block in _2b955d32d83860aab334e965cd2aecff'
  plugins/redmine_risks/app/views/risks/_list.html.erb:4:in `_2b955d32d83860aab334e965cd2aecff'
  plugins/redmine_risks/app/views/risks/index.html.erb:17:in `_22a5ac2b6e767fc14b062e0884c75d9d'
  plugins/redmine_risks/app/controllers/risks_controller.rb:26:in `block (2 levels) in index'
  plugins/redmine_risks/app/controllers/risks_controller.rb:21:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

My Plattform Data
Environment:
  Redmine version                3.4.6.stable.17615
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  additionals                    2.0.20
  clipboard_image_paste          1.13
  computed_custom_field          1.0.7
  customfield_checkbox_utility   0.0.2
  event_notifications            2.4.1
  hide_journal_details           0.0.2
  pdf_export_redmine             0.0.2
  plantuml                       0.5.1
  project_tree                   1.0.3
  redmine_auto_private           0.0.1
  redmine_banner                 0.1.2
  redmine_ckeditor               1.1.7
  redmine_custom_css             0.1.7
  redmine_cut_tag                2.0.8
  redmine_default_custom_query   1.3.0
  redmine_didyoumean             1.2.0
  redmine_glossary               0.9.3
  redmine_group_macro            0.1.0
  redmine_impersonate            1.0.0
  redmine_issue_favicon          0.1.0
  redmine_issue_templates        0.2.1
  redmine_issue_todo_lists       1.2
  redmine_issues_macros          0.0.1
  redmine_landing_page           0.1.1
  redmine_ldap_sync              2.1.0
  redmine_message_customize      0.1.0
  redmine_my_page_paginations    1.0.2
  redmine_page_break_macro       1.0.0
  redmine_per_project_formatting 0.0.5
  redmine_preview_inline         1.0.2
  redmine_risks                  1.1.2
  redmine_scheduling_poll        4.1.0
  redmine_shortcuts              0.3.0
  redmine_silencer               0.4.3
  redmine_subtask_list_accordion 1.3.2
  redmine_subtasks_inherited_fields 1.1.1
  redmine_tags                   3.2.2
  redmine_tint_issues            1.0.2
  redmine_wiki_books             0.0.5
  redmine_wiki_extensions        0.8.2
  redmine_wiki_issue_fields      0.5.9
  redmine_wiki_lists             0.0.9
  redmine_wiki_unc               0.0.4
  silent_statuses                1.0
  view_customize                 2.5.0

**Comment by xel1045** [comment]
This plugin requires Redmine 4.2 and later.
